version: '3.8'

services:
  # База данных для хранения истории
  db:
    image: postgres:15-alpine
    container_name: ml-summarization-service-db-1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: summarization_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d summarization_db"]
      interval: 5s
      timeout: 5s
      retries: 5

# Система версионирования экспериментов
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: ml-summarization-service-mlflow-1
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_HTTP_HOST_ALLOWLIST=*
    # Мы добавляем флаг --dev, чтобы убрать строгие проверки заголовков (только для разработки!)
    command: mlflow server --host 0.0.0.0 --dev

  api:
    build: .
    container_name: ml-summarization-service-api-1
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_started

  bot:
    build: .
    container_name: ml-summarization-service-bot-1
    command: python tg_bot.py
    env_file:
      - .env
    depends_on:
      - api